// Type contract for asset data generated by scripts/build-mobile.mjs.
// Allows type checking before the generated implementation exists.
export declare const embeddedWasmViewerAssets: Array<{
  path: string;
  encoding: "text" | "base64";
  content: string;
}>;
