import esbuild from "esbuild";
import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(scriptDir, "..");
const viewerDir = resolve(repoRoot, "wasm-viewer");
const mobileSrcDir = resolve(repoRoot, "mobile-src");
const generatedAssetsPath = resolve(mobileSrcDir, "wasmViewerAssets.generated.ts");
const distDir = resolve(repoRoot, ".mobile-dist");

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Source: https://github.com/vincentlaucsb/obsidian-csvzall
*/`;

function fail(message) {
  throw new Error(`Mobile build failed: ${message}`);
}

function normalizePath(path) {
  return path.replace(/\\/g, "/");
}

function listFiles(directory) {
  return readdirSync(directory, { withFileTypes: true })
    .flatMap((entry) => {
      const path = join(directory, entry.name);
      return entry.isDirectory() ? listFiles(path) : [path];
    })
    .sort((a, b) => normalizePath(a).localeCompare(normalizePath(b)));
}

function jsString(value) {
  return JSON.stringify(value)
    .replace(/\u2028/g, "\\u2028")
    .replace(/\u2029/g, "\\u2029");
}

function generateEmbeddedAssetModule() {
  if (!existsSync(join(viewerDir, "index.html")) || !existsSync(join(viewerDir, "assets"))) {
    fail("wasm-viewer assets are missing; run npm run sync:wasm-viewer first");
  }

  const assets = listFiles(viewerDir).map((path) => {
    const relativePath = normalizePath(relative(repoRoot, path));
    return {
      path: relativePath,
      encoding: "base64",
      content: readFileSync(path).toString("base64"),
    };
  });

  const body = assets
    .map((asset) => [
      "  {",
      `    path: ${jsString(asset.path)},`,
      `    encoding: ${jsString(asset.encoding)},`,
      `    content: ${jsString(asset.content)},`,
      "  },",
    ].join("\n"))
    .join("\n");

  writeFileSync(
    generatedAssetsPath,
    [
      "export type EmbeddedWasmViewerAsset = {",
      "  path: string;",
      '  encoding: "text" | "base64";',
      "  content: string;",
      "};",
      "",
      "export const embeddedWasmViewerAssets: EmbeddedWasmViewerAsset[] = [",
      body,
      "];",
      "",
    ].join("\n"),
  );
}

function readJson(path) {
  return JSON.parse(readFileSync(path, "utf8"));
}

function writeJson(path, value) {
  writeFileSync(path, `${JSON.stringify(value, null, 2)}\n`);
}

function mobileManifest() {
  const manifest = readJson(resolve(mobileSrcDir, "manifest.json"));
  if (manifest.id !== "csvzall-mobile") {
    fail(`mobile manifest must use id "csvzall-mobile", got ${manifest.id}`);
  }
  if (manifest.isDesktopOnly !== false) {
    fail("mobile manifest must set isDesktopOnly=false");
  }
  return manifest;
}

function mobileVersions() {
  const manifest = mobileManifest();
  return {
    [manifest.version]: manifest.minAppVersion,
  };
}

function mobileReadme() {
  return `# csvzall Mobile

<img src="https://raw.githubusercontent.com/vincentlaucsb/csvzall/refs/heads/master/assets/csvzall-logo-theme-safe.png" alt="csvzall logo: a reciprocating saw cutting through a spreadsheet" width="760">

Open and edit CSV files directly inside Obsidian mobile with the bundled
csvzall WASM viewer.

csvzall Mobile is the phone and tablet companion to
[csvzall for Obsidian](https://github.com/vincentlaucsb/obsidian-csvzall). It
does not install the desktop helper binary and does not require a local server.

If csvzall Mobile saves you time, please star this repository. It helps other
Obsidian users find the plugin and helps me gauge demand for continued mobile
support.

## What It Does

- Opens \`.csv\` files in an Obsidian mobile pane.
- Loads the bundled WASM viewer without installing a desktop helper binary.
- Supports basic CSV editing and saving back to the vault file.
- Includes an Obsidian-style mobile toolbar button for opening navigation.
- Stays inert on desktop so it does not compete with the desktop csvzall plugin
  for CSV ownership.

## Requirements

- Obsidian mobile.
- A vault containing \`.csv\` files.
- No external \`csvzall\` binary is required.

## Desktop Version

For desktop-native features such as chart generation, SQLite queries, large-file
viewing through the native helper process, and managed helper binary updates,
install [csvzall for Obsidian](https://github.com/vincentlaucsb/obsidian-csvzall).

It is safe to keep both plugins in the same synced vault. The desktop plugin is
desktop-only, and csvzall Mobile only registers itself as a CSV handler on
Obsidian mobile.

## Privacy and Network Use

csvzall Mobile does not collect telemetry and does not download executable code
at runtime. The WASM viewer assets are embedded in \`main.js\` and materialized
into the plugin directory when the plugin loads.

## Limitations

- Mobile support is focused on CSV viewing and editing.
- Charts, SQLite queries, and desktop helper-process features live in the
  desktop plugin.
- Very large files may still exceed what a mobile device can comfortably hold in
  memory.

## Development

This repository is generated from
[vincentlaucsb/obsidian-csvzall](https://github.com/vincentlaucsb/obsidian-csvzall).
Do not edit generated plugin assets here by hand; make source changes in the
desktop/source repository and sync this distribution repo.
`;
}

function mobileAgents() {
  return `# Repository Guide

This repository is generated from \`vincentlaucsb/obsidian-csvzall\`.

- Do not edit \`main.js\`, \`styles.css\`, \`manifest.json\`, or \`versions.json\` directly here.
- Make source changes in \`obsidian-csvzall\`, then run \`npm run sync:mobile-repo\`.
- The mobile bundle must not contain Node.js or Electron APIs.
- Obsidian Community releases should attach only \`main.js\`, \`manifest.json\`, and \`styles.css\`.
`;
}

function releaseWorkflow() {
  return `name: Release

on:
  push:
    tags:
      - "[0-9]*.[0-9]*.[0-9]*"
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag to publish assets to, for example 0.1.0"
        required: true
        type: string

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: \${{ github.event_name == 'workflow_dispatch' && inputs.tag || github.ref }}

      - name: Resolve release tag
        id: release-tag
        shell: bash
        run: |
          if [[ "\${{ github.event_name }}" == "workflow_dispatch" ]]; then
            tag="\${{ inputs.tag }}"
          else
            tag="\${GITHUB_REF_NAME}"
          fi
          echo "tag=\${tag}" >> "\${GITHUB_OUTPUT}"

      - name: Verify mobile bundle
        shell: bash
        run: |
          tag="\${{ steps.release-tag.outputs.tag }}"
          version="$(node -p "require('./manifest.json').version")"
          if [[ "\${version}" != "\${tag}" ]]; then
            echo "manifest.json version (\${version}) must match release tag (\${tag})." >&2
            exit 1
          fi
          node - <<'NODE'
          const { readFileSync } = require("fs");
          const manifest = JSON.parse(readFileSync("manifest.json", "utf8"));
          const main = readFileSync("main.js", "utf8");
          if (manifest.isDesktopOnly !== false) {
            throw new Error("csvzall Mobile must keep isDesktopOnly=false.");
          }
          const banned = [
            /require\\(["'](?:node:)?(?:child_process|crypto|electron|fs|fs\\/promises|http|https|os|path|zlib)["']\\)/,
            /\\bchild_process\\b/,
            /\\bfs\\/promises\\b/,
            /\\bnode:/,
          ];
          for (const pattern of banned) {
            if (pattern.test(main)) {
              throw new Error(\`main.js contains a desktop-only API marker: \${pattern}\`);
            }
          }
          if (!main.includes("csvzall-mobile-embedded-wasm-viewer-v1")) {
            throw new Error("main.js is missing the embedded WASM viewer marker.");
          }
          if (!main.includes("isMobileApp")) {
            throw new Error("main.js must gate plugin registration to Obsidian mobile.");
          }
          NODE

      - name: Generate release asset attestations
        uses: actions/attest@v4
        with:
          subject-path: |
            manifest.json
            main.js
            styles.css

      - name: Publish Obsidian release assets
        env:
          GH_TOKEN: \${{ github.token }}
        shell: bash
        run: |
          tag="\${{ steps.release-tag.outputs.tag }}"
          assets=(manifest.json main.js styles.css)
          if gh release view "\${tag}" >/dev/null 2>&1; then
            gh release upload "\${tag}" "\${assets[@]}" --clobber
          else
            gh release create "\${tag}" "\${assets[@]}" \\
              --title "\${tag}" \\
              --notes "Release \${tag}"
          fi
`;
}

function validateWorkflow() {
  return `name: Validate

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Verify mobile bundle
        shell: bash
        run: |
          node - <<'NODE'
          const { readFileSync } = require("fs");
          const manifest = JSON.parse(readFileSync("manifest.json", "utf8"));
          const main = readFileSync("main.js", "utf8");
          if (manifest.id !== "csvzall-mobile" || manifest.isDesktopOnly !== false) {
            throw new Error("manifest.json is not a mobile csvzall manifest.");
          }
          const banned = [
            /require\\(["'](?:node:)?(?:child_process|crypto|electron|fs|fs\\/promises|http|https|os|path|zlib)["']\\)/,
            /\\bchild_process\\b/,
            /\\bfs\\/promises\\b/,
            /\\bnode:/,
          ];
          for (const pattern of banned) {
            if (pattern.test(main)) {
              throw new Error(\`main.js contains a desktop-only API marker: \${pattern}\`);
            }
          }
          if (!main.includes("csvzall-mobile-embedded-wasm-viewer-v1")) {
            throw new Error("main.js is missing the embedded WASM viewer marker.");
          }
          if (!main.includes("isMobileApp")) {
            throw new Error("main.js must gate plugin registration to Obsidian mobile.");
          }
          NODE
`;
}

async function buildMobileBundle() {
  rmSync(distDir, { recursive: true, force: true });
  mkdirSync(distDir, { recursive: true });
  mkdirSync(resolve(distDir, ".github", "workflows"), { recursive: true });

  await esbuild.build({
    banner: {
      js: banner,
    },
    entryPoints: [resolve(mobileSrcDir, "main.ts")],
    bundle: true,
    external: [
      "obsidian",
      "@codemirror/autocomplete",
      "@codemirror/collab",
      "@codemirror/commands",
      "@codemirror/language",
      "@codemirror/lint",
      "@codemirror/search",
      "@codemirror/state",
      "@codemirror/view",
      "@lezer/common",
      "@lezer/highlight",
      "@lezer/lr",
    ],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: false,
    treeShaking: true,
    outfile: resolve(distDir, "main.js"),
    minify: true,
  });

  writeJson(resolve(distDir, "manifest.json"), mobileManifest());
  writeJson(resolve(distDir, "versions.json"), mobileVersions());
  writeFileSync(resolve(distDir, "README.md"), mobileReadme());
  writeFileSync(resolve(distDir, "AGENTS.md"), mobileAgents());
  writeFileSync(resolve(distDir, ".gitignore"), "data.json\nnode_modules/\n*.log\n*.tmp\n.DS_Store\nThumbs.db\n");
  writeFileSync(resolve(distDir, ".github", "workflows", "release.yml"), releaseWorkflow());
  writeFileSync(resolve(distDir, ".github", "workflows", "validate.yml"), validateWorkflow());
  copyFileSync(resolve(repoRoot, "LICENSE"), resolve(distDir, "LICENSE"));
  copyFileSync(resolve(repoRoot, "styles.css"), resolve(distDir, "styles.css"));
}

generateEmbeddedAssetModule();
await buildMobileBundle();

const mainSize = statSync(resolve(distDir, "main.js")).size;
console.log(`Built csvzall Mobile distribution in ${distDir} (${mainSize} bytes main.js).`);
